db_server:
  restart: always
  image: postgres
  container_name: db_server
  volumes:
    - /data/postgresql/db:/var/lib/postgresql/data
  net: bridgeNet

app_server:
  restart: always
  image: pythonFlask
  container_name: app_server
  volumes:
    - /data/python/app/files:/usr/src/python/files
  net: bridgeNet

web_server:
  restart: always
  image: nginx
  container_name: web_server
  ports:
    - "443:443"
  volumes:
    - /data/nginx/log:/var/log/nginx
  net: bridgeNet
