apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    run: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    protocol: TCP
  selector:
    run: {{ .Values.name }}
