apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        run: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: nginx
        ports:
        - containerPort: {{ .Values.port }}
